version: '3.8'

services:
  postgres:
    container_name: contacts-postgres
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.26
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    environment:
      MIX_ENV: dev
    env_file:
      - .dev.env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    networks:
      - postgres
    command: './dev.sh'

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: